// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQD2zWjPEY_J1n3RRReJAXS-ZysJb6Ig',
    appId: '1:886314317097:web:5220a98a4dcfdac433b338',
    messagingSenderId: '886314317097',
    projectId: 'to-do-app-e6daa',
    authDomain: 'to-do-app-e6daa.firebaseapp.com',
    storageBucket: 'to-do-app-e6daa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8FgQZy5GmzbdFw_TO4YsTZr0bHtg41J0',
    appId: '1:886314317097:android:afab5a83f4ad1e4d33b338',
    messagingSenderId: '886314317097',
    projectId: 'to-do-app-e6daa',
    storageBucket: 'to-do-app-e6daa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJvDTw5CZOWOqrC0zVSeYjEeaJvTRjas',
    appId: '1:886314317097:ios:8297d5a031f23d7b33b338',
    messagingSenderId: '886314317097',
    projectId: 'to-do-app-e6daa',
    storageBucket: 'to-do-app-e6daa.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBJvDTw5CZOWOqrC0zVSeYjEeaJvTRjas',
    appId: '1:886314317097:ios:8297d5a031f23d7b33b338',
    messagingSenderId: '886314317097',
    projectId: 'to-do-app-e6daa',
    storageBucket: 'to-do-app-e6daa.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClQD2zWjPEY_J1n3RRReJAXS-ZysJb6Ig',
    appId: '1:886314317097:web:6bbd9f319d56f2fc33b338',
    messagingSenderId: '886314317097',
    projectId: 'to-do-app-e6daa',
    authDomain: 'to-do-app-e6daa.firebaseapp.com',
    storageBucket: 'to-do-app-e6daa.appspot.com',
  );
}
